### ISSUE TITLE
request line is terminated by \n instead of \r\n

### ISSUE THREAD

**Issue by woffs** [afonsotrepa/PocketGopher#5]
When sending an empty request (to gopher://taz.de/ in this case) the server just gets "\n". It should get "\r\n" according to RFC 1436.

**Comment by mdom** [comment]
gopher://taz.de now also accepts a newline, but i imagine a lot of servers out there won't handle a request like this.

**Comment by afonsotrepa** [comment]
Ah, good spot. It's so common for servers to accept both that it hasn't come up before but it's definitely worth a fix. 

I'll fix it right now but it might take a while for it to drop on f-droid because I don't really remember how that stuff with them works.

**Comment by afonsotrepa** [comment]
Bug fixed and app version updated, F-droid should pick up on it in a few hours.
